# Generated by Django 3.2.8 on 2021-10-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reader',
        ),
    ]
