# Generated by Django 3.2.8 on 2021-10-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelves',
            name='book',
        ),
        migrations.AddField(
            model_name='shelves',
            name='book',
            field=models.ManyToManyField(blank=True, to='capstone_app.Book'),
        ),
    ]
