# Generated by Django 3.2.8 on 2021-10-19 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0002_remove_book_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
