# Generated by Django 3.2.8 on 2021-10-12 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0002_auto_20211012_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingupdate',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='capstone_app.book'),
        ),
    ]
