# Generated by Django 3.2.8 on 2021-10-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0003_book_reader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
