# Generated by Django 3.2.8 on 2021-10-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0003_readingupdate_number_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingupdate',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='LikeUpdate',
        ),
    ]
