# Generated by Django 3.2.8 on 2021-10-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0003_alter_readingupdate_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='default-user.png', upload_to=''),
        ),
    ]
