# Generated by Django 3.2.8 on 2021-10-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0006_readingupdate_number_of_commets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingupdate',
            old_name='number_of_commets',
            new_name='number_of_comments',
        ),
    ]
