# Generated by Django 3.2.8 on 2021-10-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0006_alter_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='default.jpeg', upload_to='capstone_app/images'),
        ),
    ]
