# Generated by Django 3.2.8 on 2021-10-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0008_alter_readingupdate_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingupdate',
            name='time',
            field=models.DateField(default='2021-10-21'),
        ),
    ]
