# Generated by Django 3.2.8 on 2021-10-26 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0009_rename_post_comments_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reader',
        ),
        migrations.AddField(
            model_name='book',
            name='reader',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
