# Generated by Django 3.2.8 on 2021-10-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0009_readingupdate_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingupdate',
            old_name='time',
            new_name='date',
        ),
    ]
