# Generated by Django 3.2.8 on 2021-10-26 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0010_auto_20211026_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reader',
        ),
        migrations.AddField(
            model_name='book',
            name='reader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reader', to=settings.AUTH_USER_MODEL),
        ),
    ]
