# Generated by Django 3.2.8 on 2021-10-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0010_alter_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='images/default.jpeg', upload_to='media/'),
        ),
    ]
