# Generated by Django 3.2.8 on 2021-10-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0011_auto_20211026_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingupdate',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_name', to='capstone_app.book'),
        ),
    ]
