# Generated by Django 3.2.8 on 2021-10-27 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0014_alter_readingupdate_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='book_name',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commented_post', to='capstone_app.readingupdate'),
        ),
    ]
