# Generated by Django 3.2.8 on 2021-10-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0014_alter_readingupdate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='readingupdate',
            name='date',
            field=models.DateField(default='2021-10-22'),
        ),
    ]
