# Generated by Django 3.2.8 on 2021-10-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0015_auto_20211022_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
