# Generated by Django 3.2.9 on 2021-11-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0015_auto_20211027_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
