# Generated by Django 3.2.8 on 2021-10-14 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0018_alter_user_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelves',
            name='reader',
        ),
        migrations.AddField(
            model_name='readingupdate',
            name='reader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readingupdate',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book', to='capstone_app.book'),
        ),
    ]
