# Generated by Django 3.2.9 on 2021-11-03 17:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0019_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='username'),
        ),
    ]
