# Generated by Django 3.2.8 on 2021-10-14 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0020_user_shelves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingupdate',
            name='book',
        ),
        migrations.RemoveField(
            model_name='shelves',
            name='book',
        ),
        migrations.AddField(
            model_name='shelves',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book', to='capstone_app.book'),
        ),
    ]
