# Generated by Django 3.2.9 on 2021-11-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0020_alter_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
