# Generated by Django 3.2.8 on 2021-10-14 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0022_auto_20211014_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingupdate',
            name='reader',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shelves',
        ),
        migrations.AddField(
            model_name='readingupdate',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shelves',
            name='reader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
