# Generated by Django 3.2.8 on 2021-10-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0025_remove_user_shelves'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingupdate',
            name='book',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
